
---
- name: MongoDB - Import public key
  apt_key:
    keyserver: <a href="hkp://keyserver.ubuntu.com:80">hkp://keyserver.ubuntu.com:80</a>
    id: EA312927
 
- name: MongoDB - Add repository
  apt_repository:
    filename: '/etc/apt/sources.list.d/mongodb-org-3.2.list'
    repo: 'deb <a href="http://repo.mongodb.org/apt/ubuntu">http://repo.mongodb.org/apt/ubuntu</a> xenial/mongodb-org/3.2 multiverse'
    state: present
    update_cache: yes
 
- name: MongoDB - Install MongoDB
  apt:
    name: mongodb-org
    state: present
    update_cache: yes
 
- name: MongoDB - Running state
  service:
    name: mongod
    state: started
